### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by FranjoIM** [zhangdaiwei/research#2]
```py
Traceback (most recent call last):
  File "./fraposa_runner.py", line 3, in <module>
    import fraposa as fp
  File "/Users/.../fraposa.py", line 61
    b_tilde = b - U1 @ (U1.T @ b)
                     ^
```

**Comment by FranjoIM** [comment]
Issue was resolved -- i needed to update Python and install some of the missing modules.
